completion time fix
RavidRo/service_everywhere pull request #135
Opened 2022-05-20 12:47 UTC by TommerFed

2022-05-23 10:09 UTC, aviv7 commented on api.ts
> +	completionTime: Date | undefined | string | number;
Choose 1 consistent format of Time

2022-05-23 10:09 UTC, aviv7 requested changes

2022-05-23 10:09 UTC, aviv7 commented on api.ts
> +	completionTime: Date | undefined | string | number;
Choose 1 consistent format of Time

2022-05-25 11:55 UTC, RavidRo approved these changes

2022-05-25 12:07 UTC, merged