Unassign status change dashboard
RavidRo/service_everywhere pull request #136
Opened 2022-05-22 08:51 UTC by TommerFed

2022-05-23 10:21 UTC, aviv7 requested changes

2022-05-23 10:21 UTC, aviv7 commented on dashboard/__tests__/ordersViewModelsTests.ts
> +	test('synchronise items in model', async () => {
add a check that the items are initialized correctly after "ordersViewModel.getItems()" call

2022-05-23 10:21 UTC, aviv7 commented on dashboard/src/model/ordersModel.ts
> +	updateAssignedWaiters(orderId: string, waiterIds: string[]): void {
add some small unit tests for the new functionalities of ordersModel

2022-05-25 12:06 UTC, RavidRo requested changes

2022-05-25 12:22 UTC, RavidRo approved these changes

2022-05-25 13:20 UTC, merged