Error notifications server
RavidRo/service_everywhere pull request #142
Opened 2022-06-01 11:58 UTC by domberman

2022-06-02 07:49 UTC, domberman commented
closes #82 #86  #88 #89

2022-06-03 19:06 UTC, RavidRo requested changes

2022-06-03 19:06 UTC, RavidRo commented on server/Logic/Notification/NotificationFacade.ts
> +			user: user,
Check with Tommer

2022-06-04 10:17 UTC, RavidRo approved these changes

2022-06-06 16:53 UTC, TommerFed approved these changes

2022-06-06 16:53 UTC, merged