Fixed the bug
RavidRo/service_everywhere pull request #23
Opened 2022-01-21 17:44 UTC by RavidRo

closes #16

2022-01-26 10:36 UTC, domberman requested changes

2022-01-26 10:36 UTC, domberman commented on clients/waiters_app/src/components/Orders.tsx
> +    }, 10000);
what's that?

2022-01-27 09:57 UTC, aviv7 approved these changes

2022-01-27 09:58 UTC, aviv7 approved these changes

2022-01-27 09:59 UTC, merged