server basic logic
RavidRo/service_everywhere pull request #78
Opened 2022-04-07 06:27 UTC by domberman

2022-04-07 08:20 UTC, RavidRo requested changes
Pupi Dupi

חלק מההערות חוזרות על עצמן במספר מקומות. אם הסכמת עם הערה מסוימת אז כדאי לשנות בכל המקומות שבהן היא מופיעה

2022-04-07 08:20 UTC, RavidRo commented on server/Logic/OrderNotifier.ts
> +		});
```suggestion
		notificationFacade.newOrder(guestId, newOrder.getDetails());
```

2022-04-07 08:20 UTC, RavidRo commented on server/Logic/OrderNotifier.ts
> +	}
cancelOrder returns a boolean that I guess indicating if it was canceled  or not. If will be best if before sending a notification we will check if canelOrderGuest returned true or false.
If it always returns true then changing the return type to void will be more simpler.

2022-04-07 08:20 UTC, RavidRo commented on server/Logic/Status.ts
> -}
Why it was deleted?

2022-04-07 08:35 UTC, domberman commented on package.json
>  }
yes

2022-04-07 08:35 UTC, domberman commented on server/Logic/IOrder.ts
> +	}
ok

2022-04-07 08:38 UTC, domberman commented on server/Logic/Order.ts
> +	override cancelOrderGuest(): boolean {
correct, will merge those

2022-04-07 08:46 UTC, domberman commented on server/Logic/OrderNotifier.ts
> +		});
whaaaaaaaaat

2022-04-09 11:44 UTC, RavidRo approved these changes

2022-04-09 11:45 UTC, merged