guest_app restricting api interfaces
RavidRo/service_everywhere pull request #79
Opened 2022-04-09 11:34 UTC by aviv7

2022-04-11 19:44 UTC, domberman requested changes

2022-04-11 19:44 UTC, domberman commented on guests_app/src/Networking/requests.ts
> -	login(phone_number: string): Promise<string> {
should stay login

2022-04-11 19:44 UTC, domberman commented on guests_app/src/signatures.ts
> +/*
can't you import api.ts?

2022-04-18 09:52 UTC, RavidRo approved these changes

2022-04-18 09:55 UTC, RavidRo approved these changes

2022-04-18 09:55 UTC, merged